// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseVault() {
  return window['go']['main']['App']['CloseVault']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetTTN() {
  return window['go']['main']['App']['GetTTN']();
}

export function OpenVault(arg1, arg2) {
  return window['go']['main']['App']['OpenVault'](arg1, arg2);
}

export function SelectVault() {
  return window['go']['main']['App']['SelectVault']();
}
