// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {vault} from '../models';

export function CloseVault():Promise<void>;

export function GetAppInfo():Promise<main.Response>;

export function GetGroups():Promise<Array<vault.Group>>;

export function GetTTN():Promise<number>;

export function OpenVault(arg1:string,arg2:string):Promise<main.Response>;

export function SelectVault():Promise<main.Response>;
