// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenVault(arg1:string,arg2:string):Promise<main.Response>;

export function SelectVault():Promise<main.Response>;
